stages:
  - test

test_project:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
    - coverage run -m pytest
    - coverage report
  only:
    - main
